# Generated by Django 4.2.13 on 2024-07-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("rg", models.CharField(max_length=9)),
                ("cpf", models.CharField(max_length=11)),
                ("data", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=10)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("A", "Avançado"),
                            ("I", "Intermediário"),
                            ("B", "Básico"),
                        ],
                        default="B",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
