# Generated by Django 4.2.13 on 2024-07-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("I", "Intermediário"), ("B", "Básico"), ("A", "Avançado")],
                default="B",
                max_length=1,
            ),
        ),
    ]
