# Generated by Django 4.2.13 on 2024-07-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_alter_curso_nivel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curso",
            old_name="nome",
            new_name="codigo_curso",
        ),
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("I", "Intermediário"), ("A", "Avançado"), ("B", "Básico")],
                default="B",
                max_length=1,
            ),
        ),
    ]
